---
title: "Final Project - Covid Data Analysis"
author: "Arushi Arora"
date: "12/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(httr)
library(jsonlite)
library(tidyverse)
```

Graph - cases per state
plot on map
states with highest cases
Analysis:
T-Test

```{r}
df = read.csv("C://User//arushi//Desktop//raw_data.csv",skip = 2, header = T)
```

#### Removing extra columns
```{r}
df$State.Senate.Majority.Political.Affiliation <- NULL
df$State.House.Majority.Political.Affiliation <- NULL
df$State.Attorney.General.Political.Affiliation  <- NULL
df$State.Insurance.Commissioner.Political.Affiliation  <- NULL
df$Footnotes   <- NULL
head(df,5)
```

#### Renaming column for join
```{r}
df2 <- df %>% 
  rename(
    state = State.Code,
    affiliation = Governor.Political.Affiliation
    )
head(df2,5)
```


#### Cleaning the data
```{r}
cleaned <- head(df2,51)
head(cleaned,5)
```

#### Extracting COVID data from API for merging with previous dataset
```{r warning=FALSE}
cases <- fromJSON("https://data.cdc.gov/resource/9mfq-cb36.json?submission_date=2020-10-31", flatten = TRUE)
head(cases,5)
```
#### Formatting Date
```{r warning=FALSE}
cases[[1]] <- substr(cases$submission_date, 0, 10)
head(cases,5)
```

#### Joining/Merging the dataframes
```{r}
final_df <- merge(cleaned, cases)
(final_df)
```

#### Converting total cases to numeric
```{r}
final_df <- transform(final_df, tot_cases = as.numeric(tot_cases))
(final_df)
```
```{r}
republican <- final_df[final_df$affiliation == 'Republican',]
(republican)
```


```{r}
democrat <- final_df[final_df$affiliation == 'Democrat',]
(democrat)
```
#### Total cases for republican
```{r}
republican$tot_cases
length(republican$tot_cases)
```

#### Total cases for democrat
```{r}
democrat$tot_cases
length(democrat$tot_cases)
```

```{r}
t.test(republican$tot_cases, y = democrat$tot_cases,alternative = c("two.sided"),
       mu = 0, paired = FALSE, var.equal = FALSE,
       conf.level = 0.95)
```
```{r}
dat_ggplot <- data.frame(
  value = c(republican$tot_cases,democrat$tot_cases),
  sample = c(rep("1",26), rep("2", 25))
)

library(ggplot2)

ggplot(dat_ggplot) +
  aes(x = sample, y = value) +
  geom_boxplot() +
  theme_minimal()
```


```{r}
boxplot(value ~ sample,
  data = dat_ggplot
)
```